export enum POSTS_ACTION_TYPE{
   GET_POSTS = '[POSTS] - GET_POSTS',
   GET_POSTS_FOR_PAGE = '[POSTS] -  GET_POSTS_FOR_PAGE',
   FIND_POST = '[POSTS] - FIND_POST',

   SORT_DESCRIPTION_IN_POSTS = '[POSTS] - SORT_DESCRIPTION_IN_POSTS',
   SORT_HEADERS_IN_POSTS = '[POSTS] - SORT_HEADERS_IN_POSTS',
   SORT_ID_IN_POSTS = '[POSTS] - SORT_ID_IN_POSTS',
};
